###
GET http://localhost:8080/send/commands/new-aggregate?count=3000&delay=200&worktime=200

###
GET http://localhost:8080/send/commands/aggregate?count=3000&delay=1000&worktime=100

###

GET http://localhost:8082/send/commands/aggregate?count=5000&delay=1000&worktime=100

###

GET http://localhost:8080/send/query/subscription?count=3000&delay=1000&worktime=100

###
GET http://localhost:8080/send/events?count=1000&delay=500

###
GET http://localhost:8080/send/query?count=2000&delay=500




