{
 "title": "Axon Framework Micrometer Application",
 "description": "Dashboard for Axon Framework (Micrometer) Application.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(app)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{app=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Axon Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Commands",
   "type": "singlestat",
   "description": "Total number of success commands",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "singlestat",
   "description": "Total number of failed commands",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Processed Commands",
   "type": "singlestat",
   "description": "Total number of processed\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Ingested Commands",
   "type": "singlestat",
   "description": "Total number of ingested\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Ignored Commands",
   "type": "singlestat",
   "description": "Total number of ignored\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Commands Rate",
   "type": "graph",
   "description": "Rate of ingested commands over time",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Success commands"
    },
    {
     "expr": "sum(irate(commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app, payloadType)",
     "legendFormat": "Success commands ({{payloadType}})"
    },
    {
     "expr": "sum(irate(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Failed commands"
    },
    {
     "expr": "sum(irate(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app, payloadType)",
     "legendFormat": "Failed commands ({{payloadType}})"
    },
    {
     "expr": "sum(irate(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Processed commands"
    },
    {
     "expr": "sum(irate(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app, payloadType)",
     "legendFormat": "Processed commands ({{payloadType}})"
    },
    {
     "expr": "sum(irate(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Ingested commands"
    },
    {
     "expr": "sum(irate(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app, payloadType)",
     "legendFormat": "Ingested commands ({{payloadType}})"
    },
    {
     "expr": "sum(irate(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Ignored commands"
    },
    {
     "expr": "sum(irate(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app, payloadType)",
     "legendFormat": "Ignored commands ({{payloadType}})"
    }
   ]
  },
  {
   "title": "Command Bus Capacity",
   "type": "graph",
   "description": "Returns a number between 0 and n number of threads on the Y-axis. Thus, if there are 4 threads working, the maximum capacity is 4 if every thread is active 100% of the time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(commandBus_capacity{app=\"$application\", instance=~\"$instance\"}) by (app)",
     "legendFormat": "Command bus"
    },
    {
     "expr": "sum(commandBus_capacity{app=\"$application\", instance=~\"$instance\"}) by (app, payloadType)",
     "legendFormat": "Command bus ({{payloadType}})"
    }
   ]
  },
  {
   "title": "Command Bus Latency",
   "type": "graph",
   "description": "It represent the time needed for a particular handler (command handler) to process/handle message. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.5\",  payloadType={{payloadType}})"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.75\",  payloadType={{payloadType}})"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.999\",  payloadType={{payloadType}})"
    }
   ]
  },
  { "title": "Axon Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Success Events",
   "type": "singlestat",
   "description": "Total number of success events",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_successCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "description": "Total number of failed events",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_failureCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "singlestat",
   "description": "Total number of processed\n events",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_processedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ingested Events",
   "type": "singlestat",
   "description": "Total number of ingested\n events",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ignored Events",
   "type": "singlestat",
   "description": "Total number of ignored\n events",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Events Rate",
   "type": "graph",
   "description": "Rate of ingested events over time",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(eventStore_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Success events"
    },
    {
     "expr": "sum(irate(eventStore_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Failed events"
    },
    {
     "expr": "sum(irate(eventStore_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Processed events"
    },
    {
     "expr": "sum(irate(eventStore_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ingested events"
    },
    {
     "expr": "sum(irate(eventStore_ignoredCounter_total{app=\"$application\", instance=\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ignored events"
    }
   ]
  },
  {
   "title": "Event Bus Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.5\", payloadType={{payloadType}})"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.75\", payloadType={{payloadType}})"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.999\", payloadType={{payloadType}})"
    }
   ]
  },
  {
   "title": "Event Processor Capacity",
   "type": "graph",
   "description": "Returns a number between 0 and n number of threads on the Y-axis. Thus, if there are 4 threads working, the maximum capacity is 4 if every thread is active 100% of the time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(eventProcessor_capacity{app=\"$application\", instance=~\"$instance\"})by(app, processorName)",
     "legendFormat": "Event processor ({{processorName}})"
    },
    {
     "expr": "sum(eventProcessor_capacity{app=\"$application\", instance=~\"$instance\"})by(app, processorName, payloadType)",
     "legendFormat": "Event processor  ({{processorName}},{{payloadType}})"
    }
   ]
  },
  {
   "title": "Event Processor Latency",
   "type": "graph",
   "description": "Event processor timers - Measures the time needed to process Event",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(eventProcessor_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app, processorName)",
     "legendFormat": "All timer (quantile=\"0.5\", processor={{processorName}})"
    },
    {
     "expr": "avg(eventProcessor_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app, processorName)",
     "legendFormat": "All timer (quantile=\"0.75\", processor={{processorName}})"
    },
    {
     "expr": "avg(eventProcessor_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0999\"})by(app, processorName)",
     "legendFormat": "All timer (quantile=\"0.999\", processor={{processorName}})"
    },
    {
     "expr": "avg(eventProcessor_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app, processorName, payloadType)",
     "legendFormat": "All timer (quantile=\"0.5\", payloadType={{payloadType}}, processor={{processorName}})"
    },
    {
     "expr": "avg(eventProcessor_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app, processorName, payloadType)",
     "legendFormat": "All timer (quantile=\"0.75\", payloadType={{payloadType}}, processor={{processorName}})"
    },
    {
     "expr": "avg(eventProcessor_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app, processorName, payloadType)",
     "legendFormat": "All timer (quantile=\"0.999\", payloadType={{payloadType}}, processor={{processorName}})"
    }
   ]
  },
  { "title": "Axon Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Success Queries",
   "type": "singlestat",
   "description": "Total number of success queries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "singlestat",
   "description": "Total number of failed queries",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Processed Queries",
   "type": "singlestat",
   "description": "Total number of processed\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ingested Queeries",
   "type": "singlestat",
   "description": "Total number of ingested\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ignored Queries",
   "type": "singlestat",
   "description": "Total number of ignored\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Queries Rate",
   "type": "graph",
   "description": "Rate of ingested queries over time",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Success queries"
    },
    {
     "expr": "sum(irate(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Failed queries"
    },
    {
     "expr": "sum(irate(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Processed queries"
    },
    {
     "expr": "sum(irate(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ingested queries"
    },
    {
     "expr": "sum(irate(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ignored queries"
    },
    {
     "expr": "sum(irate(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app, payloadType)",
     "legendFormat": "Success queries  ({{payloadType}})"
    },
    {
     "expr": "sum(irate(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app, payloadType)",
     "legendFormat": "Failed queries  ({{payloadType}})"
    },
    {
     "expr": "sum(irate(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app, payloadType)",
     "legendFormat": "Processed queries  ({{payloadType}})"
    },
    {
     "expr": "sum(irate(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app, payloadType)",
     "legendFormat": "Ingested queries  ({{payloadType}})"
    },
    {
     "expr": "sum(irate(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app, payloadType)",
     "legendFormat": "Ignored queries  ({{payloadType}})"
    }
   ]
  },
  {
   "title": "Query Bus Capacity",
   "type": "graph",
   "description": "Returns a number between 0 and n number of threads on the Y-axis. Thus, if there are 4 threads working, the maximum capacity is 4 if every thread is active 100% of the time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(queryBus_capacity{app=\"$application\", instance=~\"$instance\"})by(app)",
     "legendFormat": "Query bus"
    },
    {
     "expr": "sum(queryBus_capacity{app=\"$application\", instance=~\"$instance\"})by(app, payloadType)",
     "legendFormat": "Query bus  ({{payloadType}})"
    }
   ]
  },
  {
   "title": "Query Bus Latency",
   "type": "graph",
   "description": "It represent the time needed for a particular handler (query handler) to process/handle message. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.5\", payloadType={{payloadType}})"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.75\", payloadType={{payloadType}})"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app, payloadType)",
     "legendFormat": "All timer (quantile=\"0.999\", payloadType={{payloadType}})"
    }
   ]
  }
 ]
}